#pragma once

struct JobListStruct{

	CString sJobName;
	CString sUIN;
	int iHoloWidth;
	int iHoloHeight;
	int iPixelWidth;
	int iPixelHeight;
};

#define DEFAULT_SERVER_PORT					1945
#define MAX_PACKET_SIZE						4096		// bytes

#define COMMANDS_DELIMITER					'|'
#define PARAMETERS_DELIMITER				'*'
#define PACKET_END_CHARACTER				'\n'

//#define CLIENT_JOBS_LIST_REQUEST			"JOBS_LIST_REQUEST"
#define SERVER_JOBS_LIST_REPLY				"TOTAL_JOBS"
#define SERVER_JOB_DATA_COMMAND				"JOB_DATA"

//#define CLIENT_STATUS_REQUEST				"STATUS_REQUEST"
#define SERVER_STATUS_REPLY					"MY_STATUS"

//#define CLIENT_SET_REPETITION_RATE		"SET_REPETITION_RATE"
//#define CLIENT_GET_REPETITION_RATE		"GET_REPETITION_RATE"
#define SERVER_REPETITION_RATE_REPLY		"REPETITION_RATE"

//#define CLIENT_START_PRINTING				"START_PRINTING|{2AF550CA-6DF8-4CBE-906C-79E95DBD4AB7}*0*0"
//#define CLIENT_STOP_PRINTING				"STOP_PRINTING"

// example of SERVER_JOBS_LIST_REPLY :
// "TOTAL_JOBS|14\0"
// after SERVER_JOBS_LIST_REPLY command there will be amount of data:
// "JOB_DATA_COMMAND|param0*param1*param2*param3*param4*param5\0"

/*
"JOBS_LIST_REQUEST"
"STATUS_REQUEST"
"SET_REPETITION_RATE"
"GET_REPETITION_RATE"
"START_PRINTING|{2AF550CA-6DF8-4CBE-906C-79E95DBD4AB7}*0*0"
"STOP_PRINTING"
*/